
## userCreate [/v1/user]

### userCreate [POST]

#### Khái quát xử lý

* INSERT record `user` mới bằng thông tin nhận được
* Trường hợp `user.userFlag` của login user != 0, trả lỗi 403
* Trường hợp tồn tại record có `user.email` = `Parameters.email` AND `user.deletedAt` = NULL, trả lỗi `duplicateValueError`, truyền {0} = `Email`

+ Parameters
    + email: `email@example.com` (string, required) - Email
    + password: `passwordAbc` (string, required) - Password
    + name: `ABC` (string, required) - User Name
    + sectionId: `2` (string, required) - Section ID
    + joiningDate: `2021-01-01` (string, required) - Joining Date
    + userFlag: `0` (string, required) - User Flag

+ Response 201 (application/json)
    + Attributes (object)
        + id: `1` (string, required) - ID