# Group section

## sectionSearch [/v1/section]

### sectionSearch [GET]

#### Khái quát xử lý

* Trả về N record kết quả
* Trả về theo thứ tự sau:
    * Trường hợp `Parameters.sort` = 1, trả về theo thứ tự `section.id` ASC
    * Trường hợp `Parameters.sort` = 2, trả về theo thứ tự `section.name` ASC
* Về `Parameters.deleted`:
    * Chỉ nhận giá trị 0
    * Trường hợp gửi `Parameters.deleted` = 0, chỉ trả về các record có section.deletedAt = NULL
    * Trường hợp không gửi `Parameters.deleted`, trả về tất cả record
* Hạng mục `leaderName` trả về `user.name` của record có `user.id` = `section.leaderId` AND `user.deletedAt` = NULL
* Trường hợp `user.userFlag` của login user != 0, trả lỗi 403

+ Parameters
    + sort: `1` (string, required) - Sort
    + deleted: `1` (string, optional) - Deleted
    + limit: `20` (string, optional) - Limit
    + offset: `2` (string, optional) - Offset

+ Response 200 (application/json)
    + Attributes (object)
        + section: (array, optional, fixed-type)
            + (object)
                + id: `1` (string, required) - ID
                + name: `Developer` (string, required) - Section Name
                + remarks: `Abc...` (string, optional) - Remarks
                + leaderId: `1` (string, required) - Leader ID
                + leaderName: `David` (string, optional) - Leader Name
                + floorNum: `8` (string, required) - Floor Number
                + createdAt: `2021-01-10 00:00` (string, required) - Created At
                + updatedAt: `2021-01-10 00:00` (string, required) - Updated At
                + deletedAt: `2021-01-10 00:00` (string, optional) - Deleted At